# Generated by Django 2.2 on 2020-07-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateTimeField(auto_now=True)),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
            ],
        ),
    ]
