# Generated by Django 2.2 on 2020-07-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=255)),
                ('expense_amount', models.IntegerField()),
                ('expense_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
